version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecr: circleci/aws-ecr@9.0.4

jobs:
  build_and_push_image:
    machine:
      image: ubuntu-2204:2023.02.1
    parameters:
      account_id:
        default: ${AWS_ACCOUNT_ID}
        description: The 12 digit AWS id associated with the ECR account. This field is required.
        type: string
      container_registry_login:
        default: false  
        description: Enable login to different image container registries such as DockerHub, Heroku or Github. Defaults to false.
        type: boolean
      attach_workspace:
        default: false
        description: Boolean for whether or not to attach to an existing workspace. Default is false.
        type: boolean
      auth:
        description: The authentication method used to access your AWS account. Import the aws-cli orb in your config and provide the aws-cli/setup command to authenticate with your preferred method.
        type: steps
      aws_domain:
        default: amazonaws.com
        description: The AWS domain for your region, e.g., in China, the AWS domain is amazonaws.com.cn. The default value is amazonaws.com.
        type: string
      dockerfile:
        default: Dockerfile
        description: Name of the Dockerfile to use. Defaults to Dockerfile.
        type: string
      push_image:
        default: false
        description: Set to false to build an image without pushing to the repository. Defaults to true.
        type: boolean
      region:
        default: ${AWS_DEFAULT_REGION}
        description: Name of the environment variable storing your AWS region information, defaults to AWS_DEFAULT_REGION.
        type: string
      repo:
        default: "" 
        description: Name of an Amazon ECR repository.
        type: string
      tag:
        default: latest
        description: A comma-separated string containing Docker image tags to build and push (default = latest).
        type: string
      ssm_parameter_name: 
        default: "build-image"
        description: The name of the SSM parameter where the image tag will be stored.".
        type: string

      workspace_root:
        default: .
        description: Workspace root path that is either an absolute path or a path relative to the working directory. Defaults to '.' (the working directory).
        type: string
    steps:   
      - steps: <<parameters.auth>>
      - aws-ecr/ecr_login:
          region: ${AWS_DEFAULT_REGION}
      - aws-ecr/build_and_push_image:
          account_id: << parameters.account_id >>
          container_registry_login: <<parameters.container_registry_login>>
          attach_workspace: << parameters.attach_workspace >>
          auth: << parameters.auth >>
          aws_domain: << parameters.aws_domain >>
          dockerfile: << parameters.dockerfile >>
          push_image: << parameters.push_image >>
          repo: << parameters.repo >>
          tag: << parameters.tag >>
          workspace_root: << parameters.workspace_root >>
           
      - aws-ecr/push_image:
          region: << parameters.region >>
          repo: << parameters.repo >>
          tag:  << parameters.tag >>
      - run:
          name: Store Image Tag in SSM Parameter
          command: |
            aws ssm put-parameter --name "${{ parameters.ssm_parameter_name }}" --value "${{ parameters.tag }}" --type "String" --overwrite
      


workflows:
  ECR_BUILD_PUSH:
    jobs:
      - build_and_push_image:
          name: build-push-image-ecr
          auth: 
             - aws-cli/setup:
                 version: latest   
                 role_arn: arn:aws:iam::872238057757:role/Circleci  
          account_id: ${AWS_ACCOUNT_ID}
          attach_workspace: false
          aws_domain: amazonaws.com
          dockerfile: Dockerfile
          repo: build-repo
          tag: latest
          context: creds
          filters:
            branches:
              only:
                - main