version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecr: circleci/aws-ecr@9.1.0

jobs:
  build_and_push_image:
    machine:
      image: ubuntu-2204:2023.02.1
    parameters:
      account_id:
        default: ${AWS_ACCOUNT_ID}
        description: The 12 digit AWS id associated with the ECR account. This field is required.
        type: string
      container_registry_login:
        default: false  
        description: Enable login to different image container registries such as DockerHub, Heroku or Github. Defaults to false.
        type: boolean
      attach_workspace:
        default: false
        description: Boolean for whether or not to attach to an existing workspace. Default is false.
        type: boolean
      auth:
        description: The authentication method used to access your AWS account. Import the aws-cli orb in your config and provide the aws-cli/setup command to authenticate with your preferred method.
        type: steps
      aws_domain:
        default: amazonaws.com
        description: The AWS domain for your region, e.g., in China, the AWS domain is amazonaws.com.cn. The default value is amazonaws.com.
        type: string
      dockerfile:
        default: Dockerfile
        description: Name of the Dockerfile to use. Defaults to Dockerfile.
        type: string
      push_image:
        default: false
        description: Set to false to build an image without pushing to the repository. Defaults to true.
        type: boolean
      region:
        default: ${AWS_DEFAULT_REGION}
        description: Name of the environment variable storing your AWS region information, defaults to AWS_DEFAULT_REGION.
        type: string
      repo:
        default: "" 
        description: Name of an Amazon ECR repository.
        type: string
      tag:
        default: dev-${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM}-$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        description: A comma-separated string containing Docker image tags to build and push (default = latest).
        type: string
      ssm_parameter_name: 
        default: "build-image"
        description: The name of the SSM parameter where the image tag will be stored.".
        type: string

      workspace_root:
        default: .
        description: Workspace root path that is either an absolute path or a path relative to the working directory. Defaults to '.' (the working directory).
        type: string
    steps:   
      - steps: <<parameters.auth>>
      - aws-ecr/ecr_login:
          region: ${AWS_DEFAULT_REGION}
      - aws-ecr/build_and_push_image:
          account_id: << parameters.account_id >>
          container_registry_login: <<parameters.container_registry_login>>
          attach_workspace: << parameters.attach_workspace >>
          auth: << parameters.auth >>
          aws_domain: << parameters.aws_domain >>
          dockerfile: << parameters.dockerfile >>
          push_image: << parameters.push_image >>
          repo: << parameters.repo >>
          tag: << parameters.tag >>
          workspace_root: << parameters.workspace_root >>
           
      - aws-ecr/push_image:
          region: << parameters.region >>
          repo: << parameters.repo >>
          tag:  << parameters.tag >>
      - run:
          name: Store Image Tag in SSM Parameter
          command: |
            aws ssm put-parameter --name "build-image" --value "latest" --type "String" --overwrite

workflows:
  ECR_BUILD_PUSH:
    jobs:
      - build_and_push_image:
          name: build-push-image-ecr
          auth: 
             - aws-cli/setup:
                 version: latest   
                 role_arn: arn:aws:iam::872238057757:role/Circleci  
          account_id: ${AWS_ACCOUNT_ID}
          attach_workspace: false
          aws_domain: amazonaws.com
          dockerfile: Dockerfile
          repo: build-repo
          tag: dev-${CIRCLE_JOB}-${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM}-${CIRCLE_BUILD_CREATED_AT}
          context: creds
          filters:
            branches:
              only:
                - main



# ##################################Travelex Stndard########################
# ###########################################################################
# ---
# version: 2.1

# parameters:
#   BUILD_N_PUSH_ECR_IMG:
#     type: boolean
#     default: false

# orbs:
#   sts: tvx/aws-cli@0.0.14
#   aws-cli: circleci/aws-cli@4.0
#   aws-ecr: circleci/aws-ecr@9.0

# attach_workspace: &attach_workspace
#     attach_workspace:
#       at: ~/


# jobs:

#   sts:
#     circleci_ip_ranges: true
#     executor: sts/default
#     steps:
#       - checkout
#       - run:
#           name: Checking the environment
#           shell: /bin/bash
#           command: |
#             IAM_Role=$OIDC_ROLE_ARN
#             # IAM_Role="$OIDC_ROLE_ARN"

#             echo IAM_Role: $IAM_Role
#             echo export IAM_Role=$IAM_Role >> "$BASH_ENV"

#       - sts/setup:
#                 role-arn: $IAM_Role
#                 deploy-region: "eu-west-1"
#                 role-session-name: 'circleci-oidc-role'
#                 assume_with_oidc: true
#                 persist_to_workspace_path: '.aws'
#                 session-duration: '7200'

#   build-webapp-then-push-with-buildx:
#     machine:
#       image: ubuntu-2204:2023.07.2
#     environment:
#       region: $AWS_DEFAULT_REGION
#       repo: self-service-app
#       tag: latest
#       build_dir: docker/webapps
#     steps:
#       - aws-ecr/build_and_push_image:
#           attach_workspace: true
#           auth:
#             - aws-cli/setup:
#                 role_arn: $OIDC_ROLE_ARN
#           create_repo: true
#           dockerfile: Dockerfile
#           path: ${build_dir}
#           platform: linux/amd64
#           push_image: true
#           region: $AWS_DEFAULT_REGION
#           repo:  ${repo}
#           tag: ${tag}
#           workspace_root: ${build_dir}
#           account_id: $AWS_ACCOUNT_ID
#           build_path: ${build_dir}
#           repo_encryption_kms_key: arn:aws:kms:$AWS_DEFAULT_REGION:$AWS_ACCOUNT_ID:key/$UUID4_OF_KMS_KEY_ID
#           repo_encryption_type: KMS

#   build-nginx-then-push-with-buildx:
#     machine:
#       image: ubuntu-2204:2023.07.2
#     environment:
#       region: $AWS_DEFAULT_REGION
#       repo: self-service-nginx
#       tag: latest
#       build_dir: docker/nginx
#     steps:
#       - aws-ecr/build_and_push_image:
#           attach_workspace: true
#           auth:
#             - aws-cli/setup:
#                 role_arn: $OIDC_ROLE_ARN
#           create_repo: true
#           dockerfile: Dockerfile
#           path: ${build_dir}
#           platform: linux/amd64
#           push_image: true
#           region: $AWS_DEFAULT_REGION
#           repo: ${repo}
#           tag: ${tag}
#           workspace_root: ${build_dir}
#           account_id: $AWS_ACCOUNT_ID
#           build_path: ${build_dir}
#           repo_encryption_kms_key: arn:aws:kms:$AWS_DEFAULT_REGION:$AWS_ACCOUNT_ID:key/$UUID4_OF_KMS_KEY_ID
#           repo_encryption_type: KMS



# workflows:
#   version: 2
#   build-aws:
#     jobs:
#       - sts:
#           context: cloud-devops
#           filters:
#             branches:
#               only:
#                 - develop

#   build-img:
#     when: << pipeline.parameters.BUILD_N_PUSH_ECR_IMG >>
#     jobs:
#       - sts:
#           context: cloud-devops
#       - build-webapp-then-push-with-buildx:
#           requires:
#             - sts
#           filters:
#             branches:
#               only:
#                 - develop
