###########version 2###################
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  Foxweb-service:
    machine:
      image: ubuntu-2204:2023.02.1

    steps:
      - aws-ecr/build-and-push-image:
          path: .
          repo: build-repo
          tag: $CIRCLE_SHA1 


workflows:
  Foxweb-service-ecs-deployment:
    jobs:
      - Foxweb-service:
          name: Foxweb-service
          context: creds
          filters:
            branches:
              only:
                - main



